#+title: SyedKHS's Emacs Configuration
#+AUTHOR: SyedKHS
#+PROPERTY: header-args:emacs-lisp :tangle yes :results silent

* Package Management
Setup package management. Note that *use-package-always-ensure* is set to t, so we don't need to add
*:ensure t* to every use-package package specification. We also bootstrap straight.el

#+begin_src emacs-lisp
  ;; straight.el bootstrap
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name
          "straight/repos/straight.el/bootstrap.el"
          (or (bound-and-true-p straight-base-dir) user-emacs-directory)))
        (bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  ;; Install use-package via straight and make :straight t the default.
  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+end_src

* Magit
Best git interface.

#+begin_src emacs-lisp
  (use-package magit)
#+end_src

* Sane Defaults

** Disable Backup and Temp Files
Stop creating those #auto-save# and backup~ files.

#+begin_src emacs-lisp
  (setq auto-save-default nil)
  (setq create-lockfiles nil)
  (setq make-backup-files nil)
#+end_src

** Custom File
Prevent init.el from getting cluttered. Automatically create custom file if it doesn't exist.

#+begin_src emacs-lisp
  (setq custom-file (expand-file-name ".emacs.custom.el" user-emacs-directory))
  (unless (file-exists-p custom-file)
  		       (with-temp-buffer (write-file custom-file)))
  (load-file custom-file)
#+end_src

** Font Settings
Use Iosevka nerd font if it exists.

#+begin_src emacs-lisp
  (when (find-font (font-spec :name "Iosevka Nerd Font Mono"))
    (set-face-attribute 'default nil
  		      :family "Iosevka Nerd Font Mono"
  		      :height 140))
#+end_src

** Theme Settings
Use *doom-moonlight* as the default theme.

#+begin_src emacs-lisp
  (use-package doom-themes)
  (load-theme 'doom-moonlight t)
#+end_src

** Disable Native Compilation Warnings
Disables native compilation warnings and prune the cache at startup.

#+begin_src emacs-lisp
  (when (native-comp-available-p)
    (setq native-comp-async-report-warnings-errors nil)
    (native-compile-prune-cache))
#+end_src

** Disable UI clutter
Disable some built-in modes that we don't use.

#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Modern org look
Make org buffers fancy. We globally enable org-modern for all org buffers. org-modern-indent requires org-indent to be enabled.
Setting org-startup-idented to *t* makes all org-mode buffers start org-indent mode automatically at start.

#+begin_src emacs-lisp
  (use-package org-modern)
  (setq
   ;; Edit settings
   org-auto-align-tags nil
   org-tags-column 0
   org-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-insert-heading-respect-content t
   ;; Org styling, hide markup etc.
   org-hide-emphasis-markers t
   org-pretty-entities t
   org-agenda-tags-column 0
   org-ellipsis "...")
  (with-eval-after-load 'org (global-org-modern-mode))

  (use-package org-modern-indent
    :straight (:host github :repo "jdtsmith/org-modern-indent"))

  (setq org-startup-indented t)
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90)  

#+end_src
