#+title: SyedKHS's Emacs Configuration
#+AUTHOR: SyedKHS
#+PROPERTY: header-args:emacs-lisp :tangle yes :results silent

* Package Management
Setup package management. Note that *use-package-always-ensure* is set to t, so we don't need to add
*:ensure t* to every use-package package specification.

#+begin_src emacs-lisp
(require 'package)
(setq package-archives
      '(("gnu"    . "https://elpa.gnu.org/packages/")
  	("nongnu" . "https://elpa.nongnu.org/nongnu/")
  	("melpa"  . "https://melpa.org/packages/")))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
#+end_src

* Magit
Best git interface.

#+begin_src emacs-lisp
(use-package magit)
#+end_src

* Sane Defaults

** Whitespace Mode
Clearly show the whitespaces.

#+begin_src emacs-lisp :tangle no
(use-package whitespace
  :ensure nil
  :config
  (setq whitespace-style '(face tabs spaces space-mark tab-mark))
  (add-hook 'prog-mode-hook #'whitespace-mode)
  (add-hook 'prog-mode-hook #'whitespace-mode))
#+end_src

** Context Menu Mode
Built-in mode that shows context based options when right click on mouse is pressed.

#+begin_src emacs-lisp
(context-menu-mode +1)
#+end_src

** Dired Configuration
Configuration and enhancements for Dired.

#+begin_src emacs-lisp
(use-package diredfl
  :hook (dired-mode . diredfl-mode))

(require 'dired-x)
(setq-default dired-dwim-target t)
(setq dired-listing-switches "-alh")
(setq dired-kill-when-opening-new-dired-buffer t) ;; Reduce number of dired buffers open.
#+end_Src

** Disable Backup and Temp Files
Stop creating those #auto-save# and backup~ files.

#+begin_src emacs-lisp
(setq auto-save-default nil)
(setq create-lockfiles nil)
(setq make-backup-files nil)
#+end_src

** Custom File
Prevent init.el from getting cluttered. Automatically create custom file if it doesn't exist.

#+begin_src emacs-lisp
(setq custom-file (expand-file-name ".emacs.custom.el" user-emacs-directory))
(unless (file-exists-p custom-file)
  (with-temp-buffer (write-file custom-file)))
(load-file custom-file)
#+end_src

** Font Settings
Use Iosevka nerd font if it exists.

#+begin_src emacs-lisp
(when (find-font (font-spec :name "Iosevka Nerd Font Mono"))
  (set-face-attribute 'default nil
  		      :family "Iosevka Nerd Font Mono"
  		      :height 140))
#+end_src

** Theme Settings
Set the default theme.

#+begin_src emacs-lisp
(use-package doom-themes)
(load-theme 'doom-old-hope t)
#+end_src

** Disable Native Compilation Warnings
Disables native compilation warnings and prune the cache at startup.

#+begin_src emacs-lisp
(when (native-comp-available-p)
  (setq native-comp-async-report-warnings-errors 'silent)
  (native-compile-prune-cache))
#+end_src

** Disable UI clutter
Disable some built-in modes that we don't use.

#+begin_src emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
#+end_src

** Smooth Mouse Scrolling
Disable mouse acceleration and scroll the window which has cursor instead of focused one.

#+begin_src emacs-lisp
(setq mouse-wheel-progressive-speed nil) ;; don't accelerate scrolling
(setq mouse-wheel-follow-mouse 't) ;; scroll window under mouse
#+end_src

** Highlight Current Line
Highlights the line which has cursor. This is not great for normal editing but for special-purpose selection buffers it works
great. This is a built-in mode.

#+begin_src emacs-lisp
(add-hook 'dired-mode-hook 'hl-line-mode)
(add-hook 'package-menu-mode-hook 'hl-line-mode)
#+end_src

** Modern org look
Make org buffers fancy. We globally enable org-modern for all org buffers. org-modern-indent requires org-indent to be enabled.
Setting org-startup-idented to *t* makes all org-mode buffers start org-indent mode automatically at start.

#+begin_src emacs-lisp
(use-package org-modern)
(setq
 ;; Edit settings
 org-auto-align-tags nil
 org-tags-column 0
 org-catch-invisible-edits 'show-and-error
 org-special-ctrl-a/e t
 org-insert-heading-respect-content t
 ;; Org styling, hide markup etc.
 org-hide-emphasis-markers t
 org-pretty-entities t
 org-agenda-tags-column 0
 org-ellipsis "...")
(with-eval-after-load 'org (global-org-modern-mode))

(use-package org-modern-indent
  :straight (:host github :repo "jdtsmith/org-modern-indent"))

(setq org-edit-src-content-indentation 0)
(setq org-src-preserve-indentation t)
(setq org-startup-indented t)
(add-hook 'org-mode-hook #'org-modern-indent-mode 90)

(use-package org-bullets-mode
  :ensure org-bullets
  :config
  :hook org-mode)
#+end_src

** Quick Prompts
Use 'y' or 'n' instead of 'yes' or 'no' for prompts.

#+begin_src emacs-lisp
(setq use-short-answers t)
#+end_src

** Show Column Numbers
Show the column numbers (character position in line) in the modeline. This is a built-in global minor mode.

#+begin_src emacs-lisp
(column-number-mode +1) 
#+end_src

** Show Matching Brackets
Always show the matching brackets. This is a built-in global minor mode.

#+begin_src emacs-lisp
(setq show-paren-delay 0)
(show-paren-mode +1)
#+end_src

** Disable Startup Screen
Don't show the startup screen. We jump directly to the *scratch* buffer.

#+begin_src emacs-lisp
(setq inhibit-splash-screen t)
#+end_src

** Disable Bell Sound
Disable the annoying bell sound, this also disables the visual bell.

#+begin_src emacs-lisp
(setq ring-bell-function 'ignore)
#+end_src

** Line Numbers Mode
Display relative line numbers for certain buffers. Also preallocate the space for numbers on the left so we don't
have weird behaviour when scrolling or moving point through the file. This is a built-in global minor mode.

#+begin_src emacs-lisp
(setq
 display-line-numbers-type 'relative
 display-line-numbers-width-start t)

(add-hook 'prog-mode-hook 'display-line-numbers-mode)
(add-hook 'conf-mode-hook 'display-line-numbers-mode)
(add-hook 'text-mode-hook 'display-line-numbers-mode)
(add-hook 'dired-mode-hook 'display-line-numbers-mode)
#+end_src

** Save Cursor Position
Save the point position in the buffer. If we reopen the buffer the point would be at the location where we last closed
the buffer. Saves cursor position in ~/.emacs.d/places by default. This is a built-in global minor mode.

#+begin_src emacs-lisp
(save-place-mode +1)
#+end_src

** Replace Highlighted Text
By default if you have a region and you start typing Emacs won't replace that region. Instead it will type the text at
the location of the point. This mode makes it so if you select a region and type something, the entire region will be replaced.
This is a built-in global minor mode.

#+begin_src emacs-lisp
(delete-selection-mode +1)
#+end_src

** Which Key
Helpful package to show keybinds. This a built-in global minor mode.

#+begin_src emacs-lisp
(setq which-key-idle-delay 0.5)
(which-key-mode +1)
#+end_src

** Save Minibuffer History
Saves the minibuffer history. This is useful after restarts if we don't remember a command, we can just scroll up in history.
This is built-in global minor mode.

#+begin_src emacs-lisp
(savehist-mode +1)
#+end_src

** Delete Items by Moving to Trash
This makes Emacs delete stuff by moving it to trash instead of permanently deleting. We can recover file if a mistake was made.

#+begin_src emacs-lisp
(setq delete-by-moving-to-trash t)
#+end_src

** Editorconfig Support
Respect .editorconfig files. Editorconfig files specify indentation and formatting settings for various languages. This a built-in
global minor mode.

#+begin_src emacs-lisp
(require 'editorconfig)
(editorconfig-mode +1)
#+end_src

** Eldoc Mode Configuration
Configuration for Eldoc Mode. This is a built-in mode. Displays information about variables / functions in mninibuffer.

#+begin_src emacs-lisp
(setq eldoc-idle-delay 0.3)
(setq eldoc-documentation-strategy #'eldoc-documentation-compose)
(setq eldoc-echo-area-use-multiline-p nil)
(add-hook 'prog-mode-hook #'eldoc-mode) ;; Enable eldoc-mode for all programming modes.
#+end_src

** Repeat Mode
Useful for repeating keybinds without prefix keys. This a built-in mode.

#+begin_src emacs-lisp
(repeat-mode +1)
#+end_src


** Indentation Settings
All the indentation settings for every mode goes here.

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil) ;; Use spaces instead of tabs.
(setq-default tab-width 8) ;; Tab are 8 spaces long.

(setq-default c-default-style "linux")
(setq-default c-basic-offset 4) ;; Set to 4 spaces.

;; Forcefully disable indent-tabs-mode for C/C++ files since "linux" style enables them.
(add-hook 'c-mode-hook
          (lambda ()
            (setq indent-tabs-mode nil)))
(add-hook 'c++-mode-hook
          (lambda ()
            (setq indent-tabs-mode nil)))
#+end_src

** Compilation Mode
Configuration for the compile commands.

#+begin_src emacs-lisp
(setq compilation-always-kill t) ;; Kill previous compilation process before starting new one.
(setq compilation-scroll-output t) ;; Automatically go to end of the compilation buffer.
(global-set-key (kbd "<f5>") #'compile)
(global-set-key (kbd "<f6>") #'recompile)
#+end_src

** Performance Tweaks
Adjustments to make Emacs faster.

#+begin_src emacs-lisp
(setq read-process-output-max (* 4 1024 1024)) ;; Increase amount of data Emacs reads from a process (4 MB).
#+end_src

* Packages

** Must Have Modes
All the modes that are needed and don't come pre-installed go here.

#+begin_src emacs-lisp
(use-package markdown-mode)
(use-package rust-mode)
(use-package typescript-mode)
(use-package jtsx)
(use-package git-modes)
#+end_src

** Treesitter Configuration
Install treesitter grammars for certain languages and use ts-modes.

#+begin_src emacs-lisp
(setq treesit-language-source-alist
      '((tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
        (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
        (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")))

;; To actually install the grammars, run this once:
;; (mapc #'treesit-install-language-grammar (mapcar #'car treesit-language-source-alist))
#+end_src

** Sudo Edit
Edit files as root user. Do *M-x sudo-edit*

#+begin_src emacs-lisp
(use-package sudo-edit)
#+end_src

** Garbage Collector Magic Hack (gcmh)
Try to defer GC as much as possible. We try to do GC when idle and increase the maximum memory that can be allocated before
requiring GC trigger. An interactive helper function *my/time-since-last-gc* is also defined that shows the time since the last
GC trigger.

#+begin_src emacs-lisp
(defvar my-last-gc-time (current-time)
  "Time when the last garbage collection finished")

(add-hook 'post-gc-hook
  	  (lambda ()
  	    (setq my-last-gc-time (current-time))))

(defun my/time-since-last-gc ()
  "Show and return seconds since the last garbage collection."
  (interactive)
  (let ((secs (float-time (time-subtract (current-time) my-last-gc-time))))
    (when (called-interactively-p 'any)
      (message "Time since last GC: %.2f seconds" secs))
    secs))

(use-package gcmh
  :config
  (setq gcmh-idle-delay 3)
  (gcmh-mode +1))
#+end_src

** Whitespace Butler Mode
Remove trailing whitespace.

#+begin_src emacs-lisp :tangle no
(use-package ws-butler
  :config
  (setq ws-butler-keep-whitespace-before-point nil)
  (add-hook 'prog-mode-hook #'ws-butler-mode))
#+end_src

** Exec Path From Shell
Get shell environment variables.

#+begin_src emacs-lisp

(use-package exec-path-from-shell
  :config
  (exec-path-from-shell-initialize))
#+end_src

** Pdf Tools
View pdfs in Emacs. We remember the position in the pdf too with *save-place-mode*.

#+begin_src emacs-lisp
(use-package saveplace-pdf-view
  :config
  (save-place-mode +1))

(use-package pdf-tools
  :config
  (add-hook 'pdf-view-mode-hook #'pdf-view-roll-minor-mode)
  (pdf-loader-install)) ;; On demand loading. Leads to faster startup time.
#+end_src

** Surround
Quickly add/change/delete matching pairs.

#+begin_src emacs-lisp
(use-package surround
  :bind-keymap ("C-c s" . surround-keymap))
#+end_src

** Move Text
Move line/region up and down while maintaining the indentation.

#+begin_src emacs-lisp
(use-package move-text
  :config
  (move-text-default-bindings)) ;; M-<up> M-<down> are the default bindings.

(defun indent-region-advice (&rest ignored)
  "Re-indent the text in-and-around a text move."
  (let ((deactivate deactivate-mark))
    (if (region-active-p)
        (indent-region (region-beginning) (region-end))
      (indent-region (line-beginning-position) (line-end-position)))
    (setq deactivate-mark deactivate)))

(advice-add 'move-text-up :after 'indent-region-advice)
(advice-add 'move-text-down :after 'indent-region-advice)
#+end_src

** Expand Region
Incremental selection of syntactic elements.

#+begin_src emacs-lisp
(use-package expand-region
  :config
  (global-set-key (kbd "C-=") 'er/expand-region))
#+end_src

** Ace Window
Quickly switch windows.

#+begin_src emacs-lisp
(use-package ace-window
  :config
  (global-set-key (kbd "M-o") 'ace-window))
#+end_Src

** ZZZ To Char
Delete everything upto a specific char (zappping).

#+begin_src emacs-lisp
(use-package zzz-to-char
  :config
  (global-set-key (kbd "M-z") #'zzz-to-char))
#+end_src

** Multiple Cursors
Multiple cursors. Most useful package to exist!

#+begin_src emacs-lisp
(use-package multiple-cursors
  :config
  (global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
  (global-set-key (kbd "C->") 'mc/mark-next-like-this)
  (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
  (global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)
  (setq mc/always-run-for-all t)) ;; Disable confirmations for running certain commands with mc.
#+end_src

** Vterm
Fastest terminal emulator in Emacs. Built on top of libvterm. On Ubuntu *libtool* and *libtool-bin* package might be required
for building libvterm.

#+begin_src emacs-lisp
(use-package vterm
  :custom (vterm-kill-buffer-on-exit t)
  :config
  (setq vterm-max-scrollback 10000))
#+end_src

** Do the Right Thing Indent (dtrt-indent)
Try to guess indentation settings from existing code and set the appropriate variables.

#+begin_src emacs-lisp
(use-package dtrt-indent
  :config
  (dtrt-indent-global-mode +1))
#+end_src

** Orderless
Fuzzy matching in Emacs.

#+begin_src emacs-lisp
(use-package orderless
  :custom
  (completion-styles '(orderless partial-completion basic))
  (completion-category-overrides '((file (styles partial-completion))))
  (completion-category-defaults nil) ;; Disable defaults, use our settings.
  (completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring.
#+end_src

** Vertico
Enhanced minibuffer completions. We also enable recursive minibuffers and turn on mode aware commands only.

#+begin_src emacs-lisp
(setq enable-recursive-minibuffers t)
(setq read-extended-command-predicate #'command-completion-default-include-p)

(use-package vertico
  :custom
  (vertico-cycle t)
  :config
  (vertico-mode))
#+end_src

** Marginalia
Help strings and documentation in minibuffer.

#+begin_src emacs-lisp
(use-package marginalia
  :init
  (marginalia-mode))
#+end_src

** Consult
Enhanced search and navigation.

#+begin_src emacs-lisp
(use-package consult
  ;; Replace bindings. Lazily loaded by `use-package'.
  :bind (;; C-c bindings in `mode-specific-map'
         ("C-c M-x" . consult-mode-command)
         ("C-c h" . consult-history)
         ("C-c k" . consult-kmacro)
         ("C-c m" . consult-man)
         ("C-c i" . consult-info)
         ([remap Info-search] . consult-info)
         ;; C-x bindings in `ctl-x-map'
         ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
         ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
         ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
         ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
         ("C-x t b" . consult-buffer-other-tab)    ;; orig. switch-to-buffer-other-tab
         ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
         ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
         ;; Custom M-# bindings for fast register access
         ("M-#" . consult-register-load)
         ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
         ("C-M-#" . consult-register)
         ;; Other custom bindings
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ;; M-g bindings in `goto-map'
         ("M-g e" . consult-compile-error)
         ("M-g r" . consult-grep-match)
         ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
         ("M-g g" . consult-goto-line)             ;; orig. goto-line
         ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
         ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ;; M-s bindings in `search-map'
         ("M-s d" . consult-find)                  ;; Alternative: consult-fd
         ("M-s c" . consult-locate)
         ("M-s g" . consult-grep)
         ("M-s G" . consult-git-grep)
         ("M-s r" . consult-ripgrep)
         ("M-s l" . consult-line)
         ("M-s L" . consult-line-multi)
         ("M-s k" . consult-keep-lines)
         ("M-s u" . consult-focus-lines)
         ;; Isearch integration
         ("M-s e" . consult-isearch-history)
         :map isearch-mode-map
         ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
         ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
         ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
         ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
         ;; Minibuffer history
         :map minibuffer-local-map
         ("M-s" . consult-history)                 ;; orig. next-matching-history-element
         ("M-r" . consult-history))                ;; orig. previous-matching-history-element

  ;; The :init configuration is always executed (Not lazy)
  :init

  ;; Tweak the register preview for `consult-register-load',
  ;; `consult-register-store' and the built-in commands.  This improves the
  ;; register formatting, adds thin separator lines, register sorting and hides
  ;; the window mode line.
  (advice-add #'register-preview :override #'consult-register-window)
  (setq register-preview-delay 0.5)

  ;; Use Consult to select xref locations with preview
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)

  ;; Configure other variables and modes in the :config section,
  ;; after lazily loading the package.
  :config

  ;; Optionally configure preview. The default value
  ;; is 'any, such that any key triggers the preview.
  ;; (setq consult-preview-key 'any)
  ;; (setq consult-preview-key "M-.")
  ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
  ;; For some commands and buffer sources it is useful to configure the
  ;; :preview-key on a per-command basis using the `consult-customize' macro.
  (consult-customize
   consult-theme :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep consult-man
   consult-bookmark consult-recent-file consult-xref
   consult-source-bookmark consult-source-file-register
   consult-source-recent-file consult-source-project-recent-file
   ;; :preview-key "M-."
   :preview-key '(:debounce 0.1 any))

  ;; Optionally configure the narrowing key.
  ;; Both < and C-+ work reasonably well.
  (setq consult-narrow-key "<")) ;; "C-+"
#+end_src

** Embark
Context aware actions.

#+begin_src emacs-lisp
(use-package embark
  :bind
  (("C-." . embark-act)         ;; pick some comfortable binding
   ("C-;" . embark-dwim)        ;; good alternative: M-.
   ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'

  :init
  
  ;; Optionally replace the key help with a completing-read interface
  (setq prefix-help-command #'embark-prefix-help-command)
  
  ;; Show the Embark target at point via Eldoc. You may adjust the
  ;; Eldoc strategy, if you want to see the documentation from
  ;; multiple providers. Beware that using this can be a little
  ;; jarring since the message shown in the minibuffer can be more
  ;; than one line, causing the modeline to move up and down:
  
  ;; (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
  ;; (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)

  ;; Add Embark to the mouse context menu. Also enable `context-menu-mode'.
  ;; (context-menu-mode 1)
  ;; (add-hook 'context-menu-functions #'embark-context-menu 100)

  :config

  ;; Hide the mode line of the Embark live/completions buffers
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))

;; Consult users will also want the embark-consult package.
(use-package embark-consult) ; only need to install it, embark loads it after consult if found
#+end_src

** Corfu
Corfu enhances in-buffer completion with a small completion popup. The current candidates are shown in a popup below or
above the point, and can be selected by moving up and down. Corfu is the minimalistic in-buffer completion counterpart
of the Vertico minibuffer UI.

#+begin_src emacs-lisp
(use-package corfu
  :demand t ;; Don't lazy load
  :custom
  (corfu-auto nil)
  (corfu-cycle t)
  (corfu-popupinfo-delay 0.1)
  (corfu-preselect nil)
  (corfu-quit-no-match t)
  (corfu-on-exact-match 'show)
  (tab-always-indent 'complete) ;; Emacs thing, not Corfu. TAB tries to indent first and then auto-complete.
  (corfu-quit-at-boundary nil) ;; Use the separator in Corfu completions.
  :bind
  (:map corfu-map
        ("TAB" . corfu-insert)
        ("<tab>" . corfu-insert)
        ("RET" . corfu-insert)
        ("<return>" . corfu-insert)
        ("C-n" . corfu-next)
        ("C-p" . corfu-previous))
  :config
  (setq
   corfu-separator ?\s
   corfu-popupinfo-max-height 20)

  (global-corfu-mode)
  (corfu-history-mode))
#+end_src

** Flycheck
This is the modern replacement for Flymake. It supports a lot more features and a lot more languages than flymake. Sadly
Flycheck doesn't work out of the box with Eglot and some modes so we will need to do some work to get the integration right.

#+begin_src emacs-lisp
(use-package flycheck
  :config
  (setq
   flycheck-idle-delay-change 0.3
   flycheck-display-errors-delay 0.3
   flycheck-highlighting-mode nil))

(use-package flycheck-rust
  :config
  (with-eval-after-load 'rust-mode
    (add-hook 'flycheck-mode-hook #'flycheck-rust-setup))
  (with-eval-after-load 'rust-ts-mode
    (add-hook 'flycheck-mode-hook #'flycheck-rust-setup)))

(use-package flycheck-eglot
  :after (flycheck eglot)
  :config
  (global-flycheck-eglot-mode +1))
#+end_src

** Yasnippets
Snippets support in Emacs.

#+begin_src emacs-lisp
(use-package yasnippet
  :ensure t
  :config
  (setq yas-verbosity 0)
  (yas-global-mode 1)

  ;; Disable TAB key for snippet navigation
  (define-key yas-keymap (kbd "TAB") nil)
  (define-key yas-keymap (kbd "<tab>") nil)
  (define-key yas-keymap (kbd "SPC") nil)

  ;; This is key: bind TAB to nothing, allowing it to fall through
  (define-key yas-minor-mode-map (kbd "TAB") nil)
  (define-key yas-minor-mode-map (kbd "<tab>") nil)

  ;; Use C-j and C-k for navigation
  (define-key yas-keymap (kbd "C-j") 'yas-next-field-or-maybe-expand)
  (define-key yas-keymap (kbd "C-k") 'yas-prev-field))

(use-package yasnippet-snippets)
(use-package yasnippet-capf)
#+end_src

** Cape
capf extensions for corfu.

#+begin_src emacs-lisp
(use-package cape
  :init
  (add-hook 'completion-at-point-functions #'cape-file)
  (add-hook 'completion-at-point-functions #'cape-dabbrev)
  (add-hook 'completion-at-point-functions #'cape-keyword)
  (add-hook 'completion-at-point-functions #'yasnippet-capf)
  :config
  (advice-add #'yasnippet-capf            :around #'cape-wrap-noninterruptible)
  (advice-add #'cape-dabbrev              :around #'cape-wrap-noninterruptible)
  (advice-add #'cape-keyword              :around #'cape-wrap-noninterruptible)
  (advice-add #'cape-file                 :around #'cape-wrap-noninterruptible)

  ;; When LSP mode manages a buffer, set up a composed CAPF that combines
  ;; LSP completions with snippets, dabbrev, and keywords.
  (add-hook 'lsp-completion-mode-hook (lambda ()
                                        (setq-local completion-at-point-functions
                                                    (list
                                                     #'cape-file
                                                     (cape-capf-noninterruptible
                                                      (cape-capf-super
                                                       #'lsp-completion-at-point
                                                       #'yasnippet-capf
                                                       #'cape-dabbrev)))))))
#+end_src

** Emacs LSP Booster
Uses *emacs-lsp-booster* to grealy improve LSP performance.

#+begin_src emacs-lisp
(defun lsp-booster--advice-json-parse (old-fn &rest args)
  "Try to parse bytecode instead of json."
  (or
   (when (equal (following-char) ?#)
     (let ((bytecode (read (current-buffer))))
       (when (byte-code-function-p bytecode)
         (funcall bytecode))))
   (apply old-fn args)))

(advice-add (if (progn (require 'json)
                       (fboundp 'json-parse-buffer))
                'json-parse-buffer
              'json-read)
            :around
            #'lsp-booster--advice-json-parse)

(defun lsp-booster--advice-final-command (old-fn cmd &optional test?)
  "Prepend emacs-lsp-booster command to lsp CMD."
  (let ((orig-result (funcall old-fn cmd test?)))
    (if (and (not test?)                             ;; for check lsp-server-present?
             (not (file-remote-p default-directory)) ;; see lsp-resolve-final-command, it would add extra shell wrapper
             lsp-use-plists
             (not (functionp 'json-rpc-connection))  ;; native json-rpc
             (executable-find "emacs-lsp-booster"))
        (progn
          (when-let ((command-from-exec-path (executable-find (car orig-result))))  ;; resolve command from exec-path (in case not found in $PATH)
            (setcar orig-result command-from-exec-path))
          (message "Using emacs-lsp-booster for %s!" orig-result)
          (append '("emacs-lsp-booster" "--disable-bytecode" "--") orig-result))
      orig-result)))
(advice-add 'lsp-resolve-final-command :around #'lsp-booster--advice-final-command)
#+end_src

** LSP Mode
LSP client for Emacs.

#+begin_src emacs-lisp
(use-package lsp-mode
  :init
  (setq lsp-keymap-prefix "C-l")
  (defun my/lsp-mode-setup-completion ()
    (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
          '(orderless)))
  :hook (
         (c-mode . lsp)
         (c++-mode . lsp)
         (rust-mode . lsp)
         (rust-ts-mode . lsp)

         (lsp-completion-mode . my/lsp-mode-setup-completion)
         (lsp-mode . lsp-enable-which-key-integration))
  :commands (lsp lsp-deferred)
  :config
  ;; We use Corfu!
  (setq lsp-completion-provider :none)
  (setq lsp-log-io nil)
  (setq lsp-idle-delay 0.1)
  (setq lsp-auto-execute-action nil)
  (setq lsp-enable-on-type-formatting nil)
  (setq lsp-enable-file-watchers nil)
  (setq lsp-enable-indentation nil)
  (setq lsp-inlay-hint-enable nil)
  (setq lsp-headerline-breadcrumb-enable nil)
  (setq lsp-enable-symbol-highlighting nil)
  (setq lsp-semantic-tokens-enable nil)
  (setq lsp-signature-render-documentation nil))
#+end_src

** LSP Mode Goodies
Enhance LSP experience with lsp-ui and lsp-treemacs.

#+begin_src emacs-lisp
(use-package lsp-ui
  :commands lsp-ui-mode)

;; This will automatically install treemacs as dependency
(use-package lsp-treemacs
  :commands lsp-treemacs-errors-list)
#+end_src

** Language Server Configurations
Language server configurations for the required major modes comes here.

#+begin_src emacs-lisp
(require 'lsp-mode)
(define-key lsp-mode-map (kbd "C-l") lsp-command-map)

;; C/C++
(setq lsp-clients-clangd-args
      '("-j=4"
        "--background-index"
        "--clang-tidy"
        "--completion-style=detailed"
        "--header-insertion=never"
        "--header-insertion-decorators=0"))

;; Python
(use-package lsp-pyright
  :custom (lsp-pyright-langserver-command "basedpyright")
  :config
  :hook ((python-mode python-ts-mode) . (lambda ()
                                          (require 'lsp-pyright)
                                          (lsp))))

;; Rust
(setq lsp-rust-analyzer-cargo-watch-enable nil)
#+end_src

* Modes Configuration
Language specific modes configuration goes here.

** CC Mode
C/C++ modes configuration.

#+begin_src emacs-lisp
;; Make C and C++ modes respect the `tab-always-indent` variable.
(with-eval-after-load 'cc-mode
  (define-key c-mode-map   (kbd "TAB") #'indent-for-tab-command)
  (define-key c++-mode-map (kbd "TAB") #'indent-for-tab-command))
#+end_src


** JS/TS and JSX/TSX
Configure jsx and tsx files to use the jtsx modes.

#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . jtsx-tsx-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . jtsx-jsx-mode))
#+end_src
