#+title: SyedKHS's Emacs Configuration
#+AUTHOR: SyedKHS
#+PROPERTY: header-args:emacs-lisp :tangle yes :results silent

* Package Management
Setup package management. Note that *use-package-always-ensure* is set to t, so we don't need to add
*:ensure t* to every use-package package specification.

#+begin_src emacs-lisp
  (require 'package)
  (setq package-archives
        '(("gnu"    . "https://elpa.gnu.org/packages/")
  	("nongnu" . "https://elpa.nongnu.org/nongnu/")
  	("melpa"  . "https://melpa.org/packages/")))
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

* Magit
Best git interface.

#+begin_src emacs-lisp
  (use-package magit)
#+end_src

* Sane Defaults

** Disable Backup and Temp Files
Stop creating those #auto-save# and backup~ files.

#+begin_src emacs-lisp
  (setq auto-save-default nil)
  (setq create-lockfiles nil)
  (setq make-backup-files nil)
#+end_src

** Custom File
Prevent init.el from getting cluttered. Automatically create custom file if it doesn't exist.

#+begin_src emacs-lisp
  (setq custom-file (expand-file-name ".emacs.custom.el" user-emacs-directory))
  (unless (file-exists-p custom-file)
  		       (with-temp-buffer (write-file custom-file)))
  (load-file custom-file)
#+end_src

** Font Settings
Use Iosevka nerd font if it exists.

#+begin_src emacs-lisp
  (when (find-font (font-spec :name "Iosevka Nerd Font Mono"))
    (set-face-attribute 'default nil
  		      :family "Iosevka Nerd Font Mono"
  		      :height 140))
#+end_src

** Theme Settings
Use *doom-moonlight* as the default theme.

#+begin_src emacs-lisp
  (use-package doom-themes)
  (load-theme 'doom-moonlight t)
#+end_src

** Disable Native Compilation Warnings
Disables native compilation warnings and prune the cache at startup.

#+begin_src emacs-lisp
  (when (native-comp-available-p)
    (setq native-comp-async-report-warnings-errors 'silent)
    (native-compile-prune-cache))
#+end_src

** Disable UI clutter
Disable some built-in modes that we don't use.

#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Modern org look
Make org buffers fancy. We globally enable org-modern for all org buffers. org-modern-indent requires org-indent to be enabled.
Setting org-startup-idented to *t* makes all org-mode buffers start org-indent mode automatically at start.

#+begin_src emacs-lisp
  (use-package org-modern)
  (setq
   ;; Edit settings
   org-auto-align-tags nil
   org-tags-column 0
   org-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-insert-heading-respect-content t
   ;; Org styling, hide markup etc.
   org-hide-emphasis-markers t
   org-pretty-entities t
   org-agenda-tags-column 0
   org-ellipsis "...")
  (with-eval-after-load 'org (global-org-modern-mode))

  (use-package org-modern-indent
    :straight (:host github :repo "jdtsmith/org-modern-indent"))

  (setq org-startup-indented t)
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90)

  (use-package org-bullets-mode
    :ensure org-bullets
    :config
    :hook org-mode)
#+end_src

** Quick Prompts
Use 'y' or 'n' instead of 'yes' or 'no' for prompts.

#+begin_src emacs-lisp
  (setq use-short-answers t)
#+end_src

** Show Column Numbers
Show the column numbers (character position in line) in the modeline. This is a global minor mode.

#+begin_src emacs-lisp
  (column-number-mode 1) 
#+end_src

** Show Matching Brackets
Always show the matching brackets. This is a global minor mode.

#+begin_src emacs-lisp
  (setq show-paren-delay 0)
  (show-paren-mode 1)
#+end_src

** Disable Startup Screen
Don't show the startup screen. We jump directly to the *scratch* buffer.

#+begin_src emacs-lisp
  (setq inhibit-splash-screen t)
#+end_src

** Disable Bell Sound
Disable the annoying bell sound, this also disables the visual bell.

#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
#+end_src

** Line Numbers Mode
Display relative line numbers for certain buffers. Also preallocate the space for numbers on the left so we don't
have weird behaviour when scrolling or moving point through the file.

#+begin_src emacs-lisp
  (setq
   display-line-numbers-type 'relative
   display-line-numbers-width-start t)

  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (add-hook 'conf-mode-hook 'display-line-numbers-mode)
  (add-hook 'text-mode-hook 'display-line-numbers-mode)
  (add-hook 'dired-mode-hook 'display-line-numbers-mode)
#+end_src

** Save Cursor Position
Save the point position in the buffer. If we reopen the buffer the point would be at the location where we last closed
the buffer.

#+begin_src emacs-lisp
  (save-place-mode 1)
#+end_src

** Replace Highlighted Text
By default if you have a region and you start typing Emacs won't replace that region. Instead it will type the text at
the location of the point. This mode makes it so if you select a region and type something, the entire region will be replaced.

#+begin_src emacs-lisp
(delete-selection-mode 1)
#+end_src
