#+title: SyedKHS's Emacs Configuration
#+AUTHOR: SyedKHS
#+PROPERTY: header-args:emacs-lisp :tangle yes :results silent

* Package Management
Setup package management. Note that *use-package-always-ensure* is set to t, so we don't need to add
*:ensure t* to every use-package package specification.

#+begin_src emacs-lisp
  (require 'package)
  (setq package-archives
        '(("gnu"    . "https://elpa.gnu.org/packages/")
  	("nongnu" . "https://elpa.nongnu.org/nongnu/")
  	("melpa"  . "https://melpa.org/packages/")))
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

* Magit
Best git interface.

#+begin_src emacs-lisp
  (use-package magit)
#+end_src

* Sane Defaults

** Disable Backup and Temp Files
Stop creating those #auto-save# and backup~ files.

#+begin_src emacs-lisp
  (setq auto-save-default nil)
  (setq create-lockfiles nil)
  (setq make-backup-files nil)
#+end_src

** Custom File
Prevent init.el from getting cluttered. Automatically create custom file if it doesn't exist.

#+begin_src emacs-lisp
  (setq custom-file (expand-file-name ".emacs.custom.el" user-emacs-directory))
  (unless (file-exists-p custom-file)
  		       (with-temp-buffer (write-file custom-file)))
  (load-file custom-file)
#+end_src

** Font Settings
Use Iosevka nerd font if it exists.

#+begin_src emacs-lisp
  (when (find-font (font-spec :name "Iosevka Nerd Font Mono"))
    (set-face-attribute 'default nil
  		      :family "Iosevka Nerd Font Mono"
  		      :height 140))
#+end_src

** Theme Settings
Use *doom-moonlight* as the default theme.

#+begin_src emacs-lisp
  (use-package doom-themes)
  (load-theme 'doom-moonlight t)
#+end_src

** Disable Native Compilation Warnings
Disables native compilation warnings and prune the cache at startup.

#+begin_src emacs-lisp
  (when (native-comp-available-p)
    (setq native-comp-async-report-warnings-errors 'silent)
    (native-compile-prune-cache))
#+end_src

** Disable UI clutter
Disable some built-in modes that we don't use.

#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Modern org look
Make org buffers fancy. We globally enable org-modern for all org buffers. org-modern-indent requires org-indent to be enabled.
Setting org-startup-idented to *t* makes all org-mode buffers start org-indent mode automatically at start.

#+begin_src emacs-lisp
  (use-package org-modern)
  (setq
   ;; Edit settings
   org-auto-align-tags nil
   org-tags-column 0
   org-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-insert-heading-respect-content t
   ;; Org styling, hide markup etc.
   org-hide-emphasis-markers t
   org-pretty-entities t
   org-agenda-tags-column 0
   org-ellipsis "...")
  (with-eval-after-load 'org (global-org-modern-mode))

  (use-package org-modern-indent
    :straight (:host github :repo "jdtsmith/org-modern-indent"))

  (setq org-startup-indented t)
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90)

  (use-package org-bullets-mode
    :ensure org-bullets
    :config
    :hook org-mode)
#+end_src

** Quick Prompts
Use 'y' or 'n' instead of 'yes' or 'no' for prompts.

#+begin_src emacs-lisp
  (setq use-short-answers t)
#+end_src

** Show Column Numbers
Show the column numbers (character position in line) in the modeline. This is a built-in global minor mode.

#+begin_src emacs-lisp
  (column-number-mode 1) 
#+end_src

** Show Matching Brackets
Always show the matching brackets. This is a built-in global minor mode.

#+begin_src emacs-lisp
  (setq show-paren-delay 0)
  (show-paren-mode 1)
#+end_src

** Disable Startup Screen
Don't show the startup screen. We jump directly to the *scratch* buffer.

#+begin_src emacs-lisp
  (setq inhibit-splash-screen t)
#+end_src

** Disable Bell Sound
Disable the annoying bell sound, this also disables the visual bell.

#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
#+end_src

** Line Numbers Mode
Display relative line numbers for certain buffers. Also preallocate the space for numbers on the left so we don't
have weird behaviour when scrolling or moving point through the file. This is a built-in global minor mode.

#+begin_src emacs-lisp
  (setq
   display-line-numbers-type 'relative
   display-line-numbers-width-start t)

  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (add-hook 'conf-mode-hook 'display-line-numbers-mode)
  (add-hook 'text-mode-hook 'display-line-numbers-mode)
  (add-hook 'dired-mode-hook 'display-line-numbers-mode)
#+end_src

** Save Cursor Position
Save the point position in the buffer. If we reopen the buffer the point would be at the location where we last closed
the buffer. Saves cursor position in ~/.emacs.d/places by default. This is a built-in global minor mode.

#+begin_src emacs-lisp
  (save-place-mode 1)
#+end_src

** Replace Highlighted Text
By default if you have a region and you start typing Emacs won't replace that region. Instead it will type the text at
the location of the point. This mode makes it so if you select a region and type something, the entire region will be replaced.
This is a built-in global minor mode.

#+begin_src emacs-lisp
(delete-selection-mode 1)
#+end_src

** Which Key
Helpful package to show keybinds. This a built-in global minor mode.

#+begin_src emacs-lisp
  (setq which-key-idle-delay 0.5)
  (which-key-mode 1)
#+end_src

** Save Minibuffer History
Saves the minibuffer history. This is useful after restarts if we don't remember a command, we can just scroll up in history.
This is built-in global minor mode.

#+begin_src emacs-lisp
(savehist-mode 1)
#+end_src

** Delete Items by Moving to Trash
This makes Emacs delete stuff by moving it to trash instead of permanently deleting. We can recover file if a mistake was made.

#+begin_src emacs-lisp
(setq delete-by-moving-to-trash t)
#+end_src

** Editorconfig Support
Respect .editorconfig files. Editorconfig files specify indentation and formatting settings for various languages. This a built-in
global minor mode.

#+begin_src emacs-lisp
  (require 'editorconfig)
  (editorconfig-mode 1)
#+end_src

** Eldoc Mode Configuration
Configuration for Eldoc Mode. This is a built-in mode. Displays information about variables / functions in mninibuffer.

#+begin_src emacs-lisp
(setq eldoc-idle-delay 0.1)
#+end_src

** Repeat Mode
Useful for repeating keybinds without prefix keys. This a built-in mode.

#+begin_src emacs-lisp
(repeat-mode 1)
#+end_src


** Indentation Settings
All the indentation settings for every mode goes here.

#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil) ;; Use spaces instead of tabs.
  (setq-default tab-width 8) ;; Tab are 8 spaces long.

  (setq-default c-default-style "linux")
  (setq-default c-basic-offset 4) ;; Set to 4 spaces.

  ;; Forcefully disable indent-tabs-mode for C/C++ files since "linux" style enables them.
  (add-hook 'c-mode-hook
            (lambda ()
              (setq indent-tabs-mode nil)))
  (add-hook 'c++-mode-hook
            (lambda ()
              (setq indent-tabs-mode nil)))
#+end_src

** Compilation Mode
Configuration for the compile commands.

#+begin_src emacs-lisp
  (setq compilation-always-kill t) ;; Kill previous compilation process before starting new one.
  (setq compilation-scroll-output t) ;; Automatically go to end of the compilation buffer.
  (global-set-key (kbd "<f5>") #'compile)
  (global-set-key (kbd "<f6>") #'recompile)
#+end_src

** Performance Tweaks
Adjustments to make Emacs faster.

#+begin_src emacs-lisp
  (setq read-process-output-max (* 1024 1024)) ;; Increase amount of data Emacs reads from a process (1 mb).
#+end_src

* Packages
** Garbage Collector Magic Hack (gcmh)
Try to defer GC as much as possible. We try to do GC when idle and increase the maximum memory that can be allocated before
requiring GC trigger. An interactive helper function *my/time-since-last-gc* is also defined that shows the time since the last
GC trigger.

#+begin_src emacs-lisp
  (defvar my-last-gc-time (current-time)
    "Time when the last garbage collection finished")

  (add-hook 'post-gc-hook
  	  (lambda ()
  	    (setq my-last-gc-time (current-time))))

  (defun my/time-since-last-gc ()
    "Show and return seconds since the last garbage collection."
    (interactive)
    (let ((secs (float-time (time-subtract (current-time) my-last-gc-time))))
      (when (called-interactively-p 'any)
        (message "Time since last GC: %.2f seconds" secs))
      secs))

  (use-package gcmh
    :config
    (setq gcmh-idle-delay 3)
    (gcmh-mode 1))
#+end_src

** Exec Path From Shell
Get shell environment variables.

#+begin_src emacs-lisp

  (use-package exec-path-from-shell
    :config
    (when (memq window-system '(mac ns x))
      (exec-path-from-shell-initialize))
    (when (daemonp)
      (exec-path-from-shell-initialize)))
#+end_src

** Pdf Tools
View pdfs in Emacs. We remember the position in the pdf too with *save-place-mode*.

#+begin_src emacs-lisp
  (use-package saveplace-pdf-view
    :config
    (save-place-mode 1))

  (use-package pdf-tools
    :config
    (pdf-loader-install)) ;; On demand loading. Leads to faster startup time.
#+end_src

** Surround
Quickly add/change/delete matching pairs.

#+begin_src emacs-lisp
  (use-package surround
    :bind-keymap ("C-c s" . surround-keymap))
#+end_src
